xperseguers/t3ext-oidc

Classes/Service/AuthenticationService.php, Configuration/TypoScript/setup.txt
Default mapping is configured as follows (TYPO3 column = <OIDC field>):
plugin.tx_oidc.mapping {
fe_users {
username   = <contact_number>
name       = <name>
first_name = <given_name>
last_name  = <family_name>
address    = <street_address>
title      = <title>
zip        = <postal_code>
city       = <locality>
country    = <country>
}
}
It is possible to use multiple OIDC fields or constants in the mapping:
username = user_<contact_number>
name = <family_name>, <given_name>
It is possible to apply stdWrap to a field:
username = <contact_number>
username.wrap = user_|
Resolves: #14
=> [FEATURE] Allow custom mapping from OIDC to TYPO3

Classes/Service/AuthenticationService.php
Due to some changes, $GLOBALS['TSFE']->id may not be (yet)
available. This is typically the case on TYPO3 v8 LTS.
In addition, make sure a default mapping is returned when
a custom one has not been configured.
Resolves: #22
=> [BUGFIX] Prevent empty mapping when authenticating

composer.json, ext_emconf.php, ext_localconf.php
Once the compatibility with CMS < 10 is lifted, the class alias can be removed.
=> [TASK] Make extension compatible with TYPO3 v10

Classes/Service/AuthenticationService.php
This PR adds a signal to the AuthenticationService which is dispatched when a user is retrieved from the OID server (e.g. a user login was successful). Signal parameter is the user data.
The user data is previously extended with the access token issued by the OID server so it can by used by a signal slot for further actions.
Fixes #48 
Use case:
Some OID servers allow further API calls using the issued token to retrieve additional data besides /userinfo. E.g. [Cyclos](https://wiki4.cyclos.org/index.php/OpenID_Connect_-_OAuth2) allows to retrieve the users account status & history, it is useful (and important to us) to show this data in a Typo page.
Thanks in advance for including this in one of the next releases!
=> [FEATURE] Add signal to re-use access token retrieved on login

Classes/Service/AuthenticationService.php
v1.0.0 of the extension uses `SaltFactory::getDefaultHashInstance(TYPO3_MODE)` instead of the `GeneralUtility::makeInstance(SaltFactory::class)->getDefaultHashInstance(TYPO3_MODE)` suggested in the [developers guide](https://docs.typo3.org/c/typo3/cms-saltedpasswords/master/en-us/DevelopersGuide/Index.html). 
This causes errors like this:
```
Core: Error handler (FE): PHP Runtime Deprecation Notice: Non-static method TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashFactory::getDefaultHashInstance() should not be called statically in [...]/typo3conf/ext/oidc/Classes/Service/AuthenticationService.php line 288
```
This PR fixes this error & #47.
=> Fixes #47: static use of SaltFactory

Classes/Controller/LoginController.php, Classes/Service/AuthenticationService.php, Classes/Service/OAuthService.php, README.md, Resources/Private/Language/locallang_db.xlf, ext_conf_template.txt
This branch adds support for the Authentication workflow with dedicated Login action.
Related to #55
=> Add PKCE support

Classes/Service/AuthenticationService.php
=> [BUGFIX] Respect usersStoragePid

Classes/Controller/LoginController.php, Classes/Event/AuthenticationGetUserEvent.php, Classes/Factory/GenericOAuthProviderFactory.php, Classes/Factory/OAuthProviderFactoryInterface.php, Classes/Service/AuthenticationService.php, Classes/Service/OAuthService.php, Resources/Private/Language/locallang_db.xlf, composer.json, ext_conf_template.txt, ext_emconf.php, ext_localconf.php
This pull request
- adds compatibility with TYPO3 v11
- makes oauth provider configurable
- adds an event for the getUser signal as a replacement in future versions
Resolves #78 and #81
=> Compatibility v11

Classes/Controller/AuthenticationController.php
=> [BUGFIX] Prevent PHP warning in AuthenticationController with PHP 8

ext_emconf.php
It is still needed for non-composer installations
=> [BUGFIX] Restore ext_emconf.php

Classes/Hooks/DataHandler.php
When the usergroup assignment has to be
bulk changed due to a change in tx_oidc_pattern
it is avoided to load all affected users
into memory.
Instead, process each user sequentially.
=> [TASK] Do not load all users into memory

Classes/Event/AuthenticationPreUserEvent.php, Classes/Service/AuthenticationService.php
This is useful if one needs to filter whether certain logins should be processed at all.
Example: Only process logins, where the username matches certain criteria.
=> Add event to manipulate login data before processing

Classes/AuthenticationContext.php, Classes/Controller/LoginController.php, Classes/EventListener/FrontendLoginEventListener.php, Classes/Middleware/OauthCallback.php, Classes/Security/JwtTrait.php, Classes/Service/AuthenticationService.php, Classes/Service/OpenIdConnectService.php, Classes/ViewHelpers/OidcLinkViewHelper.php, README.md, Tests/Unit/Service/OpenIdConnectServiceTest.php, Tests/UnitTests-v10.xml, composer.json
In order to support multi-head environments without sticky sessions, the data formerly stored in the PHP session is now stored inside a JWT.
Resolves: #154
Should merge https://github.com/xperseguers/t3ext-oidc/pull/153 first.
=> Replace PHP session with JWT

Classes/EventListener/FrontendLoginEventListener.php, Classes/ViewHelpers/OidcLinkViewHelper.php
The underlying provider may throw arbitrary errors.
Make sure those do not propagate to Frontend.
=> [TASK] Catch any error that may occur during auth url generation

Classes/EventListener/FrontendLoginEventListener.php, Classes/Middleware/AuthenticationUrlRequest.php, Classes/Service/OpenIdConnectService.php, Classes/ViewHelpers/OidcLinkViewHelper.php, Configuration/RequestMiddlewares.php, README.md, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Templates/Login/Login.html, ext_conf_template.txt
Instead of always generating an authentication url for every rendering of the oidc button,
create a dedicated route, which will create
the authentication URL on demand and
redirect the user there.
Related #158
=> [TASK] Use dedicated route for authorization url

Classes/Service/OpenIdConnectService.php
If some weird arbitrary URLs are called
for a website, the language may not be
identified at all.
Adjust the authentication request detection
to cope with this situation.
=> [BUGFIX] Handle missing language request attribute

composer.json
This oidc extension is not dependent on the fe_login extension.
=> [TASK] Remove fe_login extension from dependencies

Classes/Controller/LoginController.php
If a user is already logged in do not restart
the authentication process, but simply redirect
as it would happen after a successful login.
Resolves: #161
=> [BUGFIX] LoginController should redirect a logged-in user

Classes/Service/AuthenticationService.php
Class constants are marked `private` but consuming code uses late static binding with `static::` to access them. Since the constants are private, late static binding makes no sense (no subclass would be able to use the constants) and simply causes an error (access to undefined constant). This patch prevents that error from happening in e.g. https://github.com/georgringer/oidc-be.
There are two ways to solve this:
* Declare the constants `protected` or `public`.
* Or do not use late static binding.
I've chosen the latter in this case since there will not be a need to change the values of these constants or access them externally. Any subclass that chooses to override the method that does use the constants will have to return these values in another way or call the `parent::` method to …
=> [BUGFIX] Use self:: instead of static:: late binding for private constants

Classes/Service/OAuthService.php, composer.json
This adds support for new PHP versions and
fixes the issue with missing scopes
in AbstractProvider::getAccessToken.
=> [TASK] Use v2.8 of league/oauth2-client

Classes/Service/OAuthService.php, Classes/Service/OpenIdConnectService.php
OAuthService should not rely on global
variables, but should get its information
passed explicitly.
Resolves: #185
=> [BUGFIX] Use explicitly passed request instead of global request

CHANGELOG.md, Classes/Event/AuthenticationProcessMappingEvent.php, Classes/Service/AuthenticationService.php
Username and email address are now updated
when provided via mapping from IdP.
For cases where this is not desired,
a new MappingEvent is available, where
this behavior can be adjusted.
Resolves: #189
=> [!!!][BUGFIX] Allow username and email to be updated upon login

Classes/Frontend/FrontendSimulationV13.php, Configuration/Services.yaml
Fix an error where TYPO3 v12 was unable to build its DI container due to oidc dependencies on non-existent core classes.
Declare core-internal classes as public via Services.yaml Instantiate the core-internal classes via GeneralUtility::makeInstance
=> [BUGFIX] Fix DI error in TYPO3 v12 #203

Classes/Service/OAuthService.php
Classes are already used in the `getAccessToken` method
=> [TASK] Use grant classes instead of strings

Classes/Middleware/AuthenticationUrlRequest.php
If the actual provider throws some error
this would have been hidden behind the 500
status response.
Add dedicated logging for such errors.
Additionally, send the error reason as
HTTP header, since the "reason phrase" of
the status code is ignored since HTTP/2
=> [TASK] Log errors caused by AuthenticationUrlRequest middleware

composer.json, ext_localconf.php
Together with TYPO3 core fix
https://forge.typo3.org/issues/106835
the logintype and tx_oidc[code] parameters are
now excluded from cHash calculation.
Resolves: #202
=> [BUGFIX] Exclude tx_oidc[code] parameter from cHash
