xperseguers/t3ext-oidc

Classes/Service/AuthenticationService.php, Configuration/TCA/Overrides/fe_groups.php, Resources/Private/Language/locallang_db.xlf, ext_tables.sql
=> [FEATURE] Assign roles from IDS

Classes/Service/AuthenticationService.php
=> [BUGFIX] Pass empty array if user does not yet exist

Classes/Service/AuthenticationService.php, Resources/Private/Language/locallang_db.xlf, ext_conf_template.txt
Add an option that allows to revoke the access token at the end of the
login process, after using it to retrieve the user info.
=> [FEATURE] Allow to revoke access token after login

Classes/Controller/LoginController.php, Configuration/TypoScript/setup.txt
Allow to add query parameters to the authorization redirect URL via 
TypoScript.
=> [FEATURE] Login plugin: Allow to configure authorization URL parameters

Classes/Service/AuthenticationService.php
=> [BUGFIX] Use makeInstance for creating hook objects

Classes/Controller/LoginController.php
=> [BUGFIX] Prevent PHP warning in LoginController with PHP 8

Classes/Controller/LoginController.php, Classes/Service/AuthenticationService.php, Classes/ViewHelpers/OidcLinkViewHelper.php
Remove direct access to globals.
=> [TASK] Use Core ExtensionConfiguration class

Classes/Service/OAuthService.php
This uses the grant 'client_credentials'.
=> [FEATURE] Add method to retrieve access token for client

Classes/Event/ModifyUserEvent.php, Classes/Service/AuthenticationService.php
The new ModifyUserEvent allow to modify the
user record before it is inserted/updated in
the database.
=> [FEATURE] Add event for post-processing a user record

Classes/Event/ModifyResourceOwnerEvent.php, Classes/Service/AuthenticationService.php
This allows pre-processing of the resource owner
received by the server before it is converted
to a user.
Resolves: #76
=> [FEATURE] Add ModifyResourceOwnerEvent

Classes/Service/OAuthService.php, composer.json
=> [TASK] Use RequestFactory instead of direct CURL

Configuration/TypoScript/setup.typoscript
=> [TASK] Remove switchableControllerActions

Classes/Service/OAuthService.php
Minor preparation for v12 included.
=> [TASK] Code cleanup of OAuthService

Classes/Service/AuthenticationService.php
The global TYPO3_REQUEST is not yet set,
so use the information provided by the Core
through authInfo.
=> [BUGFIX] Determine FE|BE mode based on authInfo

Classes/Service/AuthenticationService.php, ext_localconf.php
=> [TASK] Code cleanup

Classes/Service/OAuthService.php
=> [BUGFIX] Only request provider default scopes if available

Classes/Service/OAuthService.php
=> [TASK] Use default scopes from ext config for token via password grant

CHANGELOG.md, Classes/Event/AuthenticationGetUserEvent.php, Classes/Event/AuthenticationPreUserEvent.php, Classes/Event/ModifyResourceOwnerEvent.php, Classes/Event/ModifyUserEvent.php, Classes/Service/AuthenticationService.php
Include a reference to the calling
authentication service in the event's data.
Resolves: #136
=> [TASK] Enhance event data

Classes/Service/OAuthService.php
If for some reason TSFE is not available, use "en" as fallback language.
Resolves: #138
=> [BUGFIX] Cope with missing TSFE

CHANGELOG.md, Classes/Event/AuthenticationFetchUserEvent.php, Classes/Service/AuthenticationService.php
=> [FEATURE] Add event to modify where-conditions for fe_users

Classes/Controller/LoginController.php, Classes/EventListener/ProcessRequestTokenListener.php, Classes/Hooks/DataHandlerOidc.php, Classes/Service/AuthenticationService.php, Configuration/Services.yaml, composer.json, ext_emconf.php, ext_localconf.php
rebase work based on this PR
https://github.com/xperseguers/t3ext-oidc/pull/144
=> TYPO3 v12 support

Classes/Event/ModifyUserEvent.php, Classes/Service/AuthenticationService.php
Allow to modify the user record based on the oidc ressource owner
=> [FEATURE] Pass oidc resource owner info to ModifyUser event

.phpstorm.meta.php, Classes/Controller/LoginController.php, Classes/Event/AuthenticationGetUserEvent.php, Classes/Hooks/DataHandlerOidc.php, Classes/Middleware/AuthenticationUrlRequest.php, Classes/Service/AuthenticationService.php, Classes/Service/OAuthService.php, Classes/Service/OpenIdConnectService.php, Classes/ViewHelpers/OidcLinkViewHelper.php, composer.json
Cleanup code accordingly.
Add SensitiveParameter attribute for passwords.
Resolves: #177
=> [TASK] Require PHP 8.1

Classes/Controller/LoginController.php, Classes/Frontend/FrontendSimulationInterface.php, Classes/Frontend/FrontendSimulationV11.php, Classes/Frontend/FrontendSimulationV12.php, Classes/Frontend/FrontendSimulationV13.php, Classes/Service/AuthenticationService.php, Classes/Service/OAuthService.php, Classes/Service/OpenIdConnectService.php, Configuration/TypoScript/setup.typoscript, composer.json, ext_emconf.php, ext_localconf.php
=> [FEATURE] Make TYPO3 v13 compatible

Classes/Frontend/FrontendSimulationV13.php
Follows https://review.typo3.org/c/Packages/TYPO3.CMS/+/87805
=> [BUGFIX] Load full TypoScript setup in TYPO3 v13
